name: Continuous Integration

on:
  pull_request: # Trigger workflow ini setiap kali ada pull request
    branches:
      - master
      - main # Tentukan branch utama Anda

jobs:
  run-tests: # Job untuk menjalankan semua tes yang sukses
    runs-on: ubuntu-latest # Menggunakan runner Ubuntu terbaru
    steps:
      - uses: actions/checkout@v4 # Checkout kode dari repository

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Menggunakan Node.js versi 20

      - name: Install dependencies
        run: npm install # Menginstal dependensi proyek

      - name: Run Unit Tests (Scenario Sukses)
        run: npm run test # Jalankan unit tests
        env:
          NODE_ENV: test

      - name: Run Integration Tests (Scenario Sukses - Menghubungkan ke AWS RDS)
        run: npm run test:integration # Jalankan integration tests
        env: # Kredensial RDS diambil dari GitHub Secrets
          RDS_DB_USER: developer
          RDS_DB_HOST: forumapi.czoqiq2k8qc3.ap-southeast-1.rds.amazonaws.com
          RDS_DB_NAME: forumapi
          RDS_DB_PASSWORD: supersecretpassword
          RDS_DB_PORT: 5432
          NODE_ENV: test

      - name: Run Functional Tests (Scenario Sukses - Menghubungkan ke AWS RDS)
        run: npm run test:watch # Jalankan functional tests
        env: # Kredensial RDS juga dibutuhkan oleh aplikasi yang diuji (jika health check konek ke DB)
          RDS_DB_USER: developer
          RDS_DB_HOST: forumapi-test.czoqiq2k8qc3.ap-southeast-1.rds.amazonaws.com
          RDS_DB_NAME: forumapi-test
          RDS_DB_PASSWORD: supersecretpassword
          RDS_DB_PORT: 5432
          NODE_ENV: test
          PORT: 5000 # Port yang digunakan functional test (sesuai tests/functional.test.js)

  failing-scenario: # Job terpisah untuk mendemonstrasikan skenario gagal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install

      - name: Deliberately Failing Test (Skenario Gagal)
        # Anda bisa mengaktifkan bagian "SKENARIO GAGAL" di tests/unit.test.js
        # Atau hanya menjalankan perintah yang pasti gagal seperti ini:
        run: |
          echo "This job is intentionally designed to fail to show a failed CI scenario."
          false # Perintah ini akan menyebabkan job ini gagal